# Generated by Django 3.2.3 on 2021-06-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washingmachine',
            name='is_wm_reserved',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
