# Generated by Django 3.2.3 on 2021-06-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0002_alter_washingmachine_is_wm_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washingmachine',
            name='motor',
        ),
        migrations.RemoveField(
            model_name='washingmachine',
            name='servo_motor',
        ),
    ]
