# Generated by Django 3.2.3 on 2021-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssystem',
            name='smartry_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
