# Generated by Django 3.2.3 on 2021-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
