# Generated by Django 3.2.3 on 2021-06-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_sensor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='code',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
