# Generated by Django 3.2.3 on 2021-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_sensor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
    ]
