# Generated by Django 3.2.3 on 2021-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLocker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_locker_use', models.BooleanField(default=False)),
                ('is_locker_reserved', models.BooleanField(default=False)),
                ('is_locker_door_open', models.BooleanField(default=False)),
                ('proximity_sensor', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('servo_motor', models.BooleanField(default=False)),
                ('is_error_occurred', models.BooleanField(default=False)),
                ('error', models.CharField(max_length=20, null=True)),
                ('is_user_matched', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
