# Generated by Django 3.2.3 on 2021-06-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartlocker',
            name='servo_motor',
        ),
    ]
